"""add is_active to students

Revision ID: 0ab9a2fd066a
Revises: ceabc332a824
Create Date: 2026-07-23 08:25:53.064829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab9a2fd066a'
down_revision: Union[str, Sequence[str], None] = 'ceabc332a824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
